### PR TITLE
Rename approved to confirmed

### PR DESCRIPTION
**Pull request by lrettig**
Including @noamnelke's feedback.

### CODE REVIEW

**Comment by lrettig** [comment]
@avive this has been hanging for a while, could you please review?

**Comment by avive** [comment]
Team any provided these colors from the spacemesh color theme as part of the explorer visual design. We should use these for now. We also need to decide on the separation between transaction state and transaction result and have color for each enum field.

**Comment by lrettig** [comment]
I removed the colors. All this does is rename the state "approved" to "confirmed."

**Review by noamnelke — APPROVED** [review]

**Comment by lrettig** [comment]
@avive your call here - thanks

**Review by avive — APPROVED** [review]
This is all changing with tx receipts and status as defined in the new api.

**Pull request merged**
